# Generated by Django 5.1.7 on 2025-11-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addbudget',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='addbudget',
            name='name',
            field=models.CharField(default='Main Budget', max_length=100),
        ),
    ]
