# Generated by Django 5.1.7 on 2025-11-02 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_addbudget_options_addbudget_name'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrecord',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='budget.addbudget'),
        ),
    ]
